
import App from './App'
// 源码用户
import { xui } from "@/uni_modules/tmx-ui/index.uts"

//多语言配置类型 从1.1.15开始改变了安装配置表，使用了类型定义。
import { Tmui4xOptions } from "@/uni_modules/tmx-ui/interface.uts"

import { createSSRApp } from 'vue'
export function createApp() {
	const app = createSSRApp(App)
	app.use(xui,
		{
			config: {
				designSize: 1440,
        maximumCalculatedSize: 2200,
			}, // 可选，tmui主题配置
			i18nOptions: null // 可选，多语言配置
		} as Tmui4xOptions
	)

	return {
		app
	}
}
